/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ct: {
          bg:               'var(--ct-bg)',
          'bg-subtle':      'var(--ct-bg-subtle)',
          surface:          'var(--ct-surface)',
          'surface-hover':  'var(--ct-surface-hover)',
          'surface-elevated':'var(--ct-surface-elevated)',
          text:             'var(--ct-text)',
          'text-secondary': 'var(--ct-text-secondary)',
          'text-tertiary':  'var(--ct-text-tertiary)',
          'text-inverse':   'var(--ct-text-inverse)',
          border:           'var(--ct-border)',
          'border-subtle':  'var(--ct-border-subtle)',
          'border-strong':  'var(--ct-border-strong)',
          accent:           'var(--ct-accent)',
          'accent-hover':   'var(--ct-accent-hover)',
          'accent-subtle':  'var(--ct-accent-subtle)',
          'accent-muted':   'var(--ct-accent-muted)',
          'accent-text':    'var(--ct-accent-text)',
          success:          'var(--ct-success)',
          'success-subtle': 'var(--ct-success-subtle)',
          'success-text':   'var(--ct-success-text)',
          warning:          'var(--ct-warning)',
          'warning-subtle': 'var(--ct-warning-subtle)',
          'warning-text':   'var(--ct-warning-text)',
          danger:           'var(--ct-danger)',
          'danger-subtle':  'var(--ct-danger-subtle)',
          'danger-text':    'var(--ct-danger-text)',
          info:             'var(--ct-info)',
          'info-subtle':    'var(--ct-info-subtle)',
          'info-text':      'var(--ct-info-text)',
        }
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display': 'var(--ct-text-display)',
        'h1': 'var(--ct-text-h1)',
        'h2': 'var(--ct-text-h2)',
        'h3': 'var(--ct-text-h3)',
        'body': 'var(--ct-text-body)',
        'sm': 'var(--ct-text-sm)',
        'xs': 'var(--ct-text-xs)',
        'meta': 'var(--ct-text-meta)',
      },
      spacing: {
        'ct-1': 'var(--ct-space-1)',
        'ct-2': 'var(--ct-space-2)',
        'ct-3': 'var(--ct-space-3)',
        'ct-4': 'var(--ct-space-4)',
        'ct-5': 'var(--ct-space-5)',
        'ct-6': 'var(--ct-space-6)',
        'ct-8': 'var(--ct-space-8)',
        'ct-10': 'var(--ct-space-10)',
        'ct-12': 'var(--ct-space-12)',
        'ct-16': 'var(--ct-space-16)',
      },
      borderRadius: {
        'ct-sm': 'var(--ct-radius-sm)',
        'ct-md': 'var(--ct-radius-md)',
        'ct-lg': 'var(--ct-radius-lg)',
        'ct-xl': 'var(--ct-radius-xl)',
      },
      boxShadow: {
        'ct-sm': 'var(--ct-shadow-sm)',
        'ct-md': 'var(--ct-shadow-md)',
        'ct-lg': 'var(--ct-shadow-lg)',
        'ct-xl': 'var(--ct-shadow-xl)',
        'ct-focus': 'var(--ct-shadow-focus)',
      },
      transitionDuration: {
        'fast': 'var(--ct-duration-fast)',
        'normal': 'var(--ct-duration-normal)',
        'slow': 'var(--ct-duration-slow)',
      },
    },
  },
  plugins: [],
}
